### ISSUE TITLE
Status - DOWN // Not able to use the scraper

### ISSUE THREAD

**Issue by jeanbono4425** [taux1c/onlyfans-scraper#17]
Heya ! 

First, I'd like to thank you for making this project !
After thoroughly filling the info asked when running the script, I'm faced with this:
```
Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\onlyfans-scraper-script.py", line 33, in <module>
    sys.exit(load_entry_point('onlyfans-scraper==2.0.0', 'console_scripts', 'onlyfans-scraper')())
  File "c:\program files\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 330, in main
    process_prompts()
  File "c:\program files\python39\lib\site-packages\onlyfans_scraper\scraper.py", line 241, in process_prompts
    model_id = profile.get_id(headers, username)
  File "c:\program files\python39\lib\site-packages\onlyfans_scraper\api\profile.py", line 73, in get_id
    r.raise_for_status()
  File "c:\program files\python39\lib\site-packages\httpx\_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://onlyfans.com/api2/v2/users/toohsakaa'
For more information check: https://httpstatuses.com/400
```

Do you have any idea on what's causing this ?

Thanks in a million !

**Comment by taux1c** [comment]
Status down generally means the login is invalid, are you sure you filled everything out correctly?

**Comment by taux1c** [comment]
What's interesting is the 400 status. 

[400 Bad Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400)
The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

**Comment by 0x3333** [comment]
You must provide all the variables exactly as they are in your browser, including the user agent, otherwise, it will fail.
