### ISSUE TITLE
not running after install

### ISSUE THREAD

**Issue by iamrobbietechie** [taux1c/onlyfans-scraper#21]
OS: Windows 10

How did you install?: pip install git+https://github.com/taux1c/onlyfans-scraper

Traceback: Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\Scripts\onlyfans-scraper-script.py", line 33, in <module>
    sys.exit(load_entry_point('onlyfans-scraper==2.0.0', 'console_scripts', 'onlyfans-scraper')())
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\Scripts\onlyfans-scraper-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\scraper.py", line 19, in <module>
    from .utils import auth, config, download, profiles, prompts
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\download.py", line 14, in <module>
    from ..constants import path_to_file
ImportError: cannot import name 'path_to_file' from 'onlyfans_scraper.constants' (C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\constants.py)

Python Version: 3.10.7

Program Version: 2.0.0

PIP Freeze:

Steps to recreate:  I ran onlyfans-scraper from command line to create auth.json, also tried it as Administrator (I'm on Windows 10) and it won't run.  I've also tried uninstalling and re-installing the script as was shown in another issue and also uninstalled and reinstalled python 3.10.7 after doing a repair of python didn't fix the issue.  I'm only trying to like posts and found this script through an older version of the like/unlike that stated it moved to this script.

--------------------------------------------------------------------------------------------
EDIT:  Tried this on Windows 11, just in case it was an OS issue and this is what came back
--------------------------------------------------------------------------------------------

C:\Users\Me>onlyfans-scraper
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\Scripts\onlyfans-scraper-script.py", line 33, in <module>
    sys.exit(load_entry_point('onlyfans-scraper==2.0.0', 'console_scripts', 'onlyfans-scraper')())
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\Scripts\onlyfans-scraper-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\scraper.py", line 19, in <module>
    from .utils import auth, config, download, profiles, prompts
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\utils\download.py", line 14, in <module>
    from ..constants import path_to_file
ImportError: cannot import name 'path_to_file' from 'onlyfans_scraper.constants' (C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\constants.py)

**Comment by taux1c** [comment]
This has been fixed, I removed the variable because some people were getting confused by it being there and I forgot about the import statement there. I have removed the import statement also.

**Comment by iamrobbietechie** [comment]
Dang, you did that fast, thank you and thank you for the awesome coding you did to make this, it is appreciated.

**Comment by taux1c** [comment]
You're welcome, and thanks for the appreciation but I can't take full credit. There are several other contributors and a lot community members that contribute. 😉 without everyone this wouldn't be where it is.
