### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by yangsss717** [taux1c/onlyfans-scraper#59]
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python310\Scripts\onlyfans-scraper-script.py", line 33, in <module>
    sys.exit(load_entry_point('onlyfans-scraper==2.0.1', 'console_scripts', 'onlyfans-scraper')())
  File "C:\Users\young\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\scraper.py", line 415, in main
    process_prompts()
  File "C:\Users\young\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\scraper.py", line 218, in process_prompts
    subscribe_count = process_me(headers)
  File "C:\Users\young\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\scraper.py", line 197, in process_me
    my_profile = me.scrape_user(headers)
  File "C:\Users\young\AppData\Local\Programs\Python\Python310\lib\site-packages\onlyfans_scraper\api\me.py", line 26, in scrape_user
    r.raise_for_status()
  File "C:\Users\young\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://onlyfans.com/api2/v2/users/me'
For more information check: https://httpstatuses.com/401

**Comment by yangsss717** [comment]
Status - DOWN

**Comment by StPatty33** [comment]
This is a dup of the most recent issue that's been open for several days.

**Comment by yangsss717** [comment]
> 这是已开放几天的最新一期的重复。

May I ask how to solve it?

**Comment by taux1c** [comment]
This repo is outdated (no longer works) and I am no longer maintaining it.
