### ISSUE TITLE
Keep getting an error

### ISSUE THREAD

**Issue by HitoSantos** [taux1c/onlyfans-scraper#78]
Hi, I followed your tutorial and input all the necessary info to run the script, but every time i select 'Download content from a user', it shows me this:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/onlyfans-scraper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/onlyfans_scraper/scraper.py", line 415, in main
    process_prompts()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/onlyfans_scraper/scraper.py", line 280, in process_prompts
    loop()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/onlyfans_scraper/scraper.py", line 218, in process_prompts
    subscribe_count = process_me(headers)
                      ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/onlyfans_scraper/scraper.py", line 197, in process_me
    my_profile = me.scrape_user(headers)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/onlyfans_scraper/api/me.py", line 26, in scrape_user
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://onlyfans.com/api2/v2/users/me'

How can I fix it?

Thanks!

**Comment by HitoSantos** [comment]
Thanks anyway, man. Hope you get back on track again soon!
